P05_DataPassingToViews/Models/Authors.cs
namespace P05_DataPassingToViews.Models
{
    public class Authors
    {
        public int AuthorID { get; set; }
        public string AuthorName { get; set; }
        public string BookName { get; set; }

    }
}

P05_DataPassingToViews/Models/Cars.cs
namespace P05_DataPassingToViews.Models
{
    public class Cars
    {
        public int CarID { get; set; }
        public string BrandName { get; set; }
        public string Family { get; set; }
        public int Year { get; set; }
    }
}

P05_DataPassingToViews/Models/ErrorViewModel.cs
namespace P05_DataPassingToViews.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

P05_DataPassingToViews/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using P05_DataPassingToViews.Models;

namespace P05_DataPassingToViews.Controllers
{
    public class AuthorController : Controller
    {
        public IActionResult Index()
        {
            // ViewBag
            // Controller --> View a veri taşımak için kullanılıyor.Tersi durum View--> Controller mümkün değil.
            // - Viewbag kullanımında sayfamızın bir refresh redirect türü işlemlerde (post işlemleri) içeriği temizlenir.
            // - eğer birden fazla aynı viewbag tanımlaması varsa en son tanımlanan geçerli oluyor.
            ViewBag.Message = "Bu bir ViewBag den gelen mesajdır...";

            // ViewData
            // Esas farkı backgroundda yani veriyi tutma şeklinde. Dictionary yapısı olarak veriyi tutuyor.(Key-Value eşleşmesi olarak)

            List<Authors> authorlist = new List<Authors>();

            authorlist.Add(new Authors() { AuthorID = 1, AuthorName = "Stephen King", BookName = "It" });
            authorlist.Add(new Authors() { AuthorID = 2, AuthorName = "Alexander Dumas", BookName = "Three Musketeers" }); 
            authorlist.Add(new Authors() { AuthorID = 3, AuthorName = "Seth Godin", BookName = "Mor İnek" });
            authorlist.Add(new Authors() { AuthorID = 4, AuthorName = "Seymen Bozaslan", BookName = "İçinden Yol Geçen Hayatlar" });
            authorlist.Add(new Authors() { AuthorID = 5, AuthorName = "Erkin Yeşil", BookName = "Türkiye'nin Macera Rotaları" }); 
            authorlist.Add(new Authors() { AuthorID = 6, AuthorName = "Ayşegül Karaçivi", BookName = "Getirin Çekicimi...Kırılacak Kabuk Var" });

            ViewBag.Message = "Bu ViewData ile taşınan bir veridir..";

            ViewData["Authors"] = authorlist;

            return View();
        }
    }
}

P05_DataPassingToViews/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using P05_DataPassingToViews.Models;

namespace P05_DataPassingToViews.Controllers
{
    public class CarController : Controller
    {
        public IActionResult Index()
        {
            List<Cars> carlist = new List<Cars>();

            carlist.Add(new Cars() { CarID = 1, BrandName = "Volvo", Family = "XC70", Year = 1995 });
            carlist.Add(new Cars() { CarID = 2, BrandName = "Volkswagen", Family = "Beetle 1974", Year = 1974 });
            carlist.Add(new Cars() { CarID = 3, BrandName = "Bugatti", Family = "Chiron", Year = 2015 });
            carlist.Add(new Cars() { CarID = 4, BrandName = "Ferrari", Family = "California", Year = 2022 });
            carlist.Add(new Cars() { CarID = 5, BrandName = "Dodge", Family = "Charger srt 8", Year = 1970 });

            ViewBag.Message = "Bu ViewData ile taşınan bir veridir..";

            return View(carlist);
        }
    }
}

P05_DataPassingToViews/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using P05_DataPassingToViews.Models;
using System.Diagnostics;

namespace P05_DataPassingToViews.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

P05_DataPassingToViews/Views/Author/Index.cshtml
@{
    ViewData["Title"] = "Authors Page";
}

<div class="text-center">
    <h1 class="display-4">YAZARLARIMIZ</h1>
    <hr />



</div>

<h1>@ViewBag.Message</h1>
<br />
<hr />
<br />
@foreach (var item in ViewData["Authors"] as List<Authors>)
{
    <p><b>@item.AuthorID</b> numaralı yazar : <b>@item.AuthorName</b> - Kitabının adı : <b>@item.BookName</b></p>
    <br />
}

P05_DataPassingToViews/Views/Car/Index.cshtml
@model List<Cars>
@{
    ViewData["Title"] = "Cars Page";
}

<div class="text-center">
    <h1 class="display-4">OUR CARS LIST</h1>
    <hr />
    <br />
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Brand Name</th>
            <th>Family</th>
            <th>Year</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.CarID</td>
                <td>@item.BrandName</td>
                <td>@item.Family</td>
                <td>@item.Year</td>
            </tr>
        }
    </table>
</div>

P05_DataPassingToViews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - P05_DataPassingToViews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/P05_DataPassingToViews.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">P05_DataPassingToViews</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index">Cars</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @* Canlı bölüm *@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - P05_DataPassingToViews - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

P05_DataPassingToViews/Views/Shared/_Layout_UK.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}